version: '3.8'
services:
  cancel-me-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - cancel-me-db:/var/lib/postgresql/data
volumes:
  cancel-me-db:
    driver: local
